/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.chatcomp;

import com.nhom11.model.Model_Recieve_Message;
import com.nhom11.model.Model_Send_Message;
import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author btdun
 */
public class Chat_Right extends javax.swing.JLayeredPane {

    /**
     * Creates new form Chat_Left
     */
    public Chat_Right() {
        initComponents();
        txt.setBackground(new Color(44,156,230));
        txt.getTxt().setForeground(Color.white);
    }
    public void setText(String text){
        if(text.equals(""))
            txt.hideText();
        else
        txt.setText(text);
//        txt.seen();
//        txt.setTime("10:30 PM");
    }
    public void setImage(Icon ... images){
        txt.setImage(true, images);
    }
    public void setImage(String ... images){
        txt.setImage(true, images);
    }
    public void setTime(String time){
        txt.setTime(time);
        txt.sendSuccessfull();
    }
    
    public void setEmoji(Model_Send_Message ms){
        txt.setEmoji(true, Integer.parseInt(ms.getText()));
    }
    public void setFile(String fileName,String fileSize){
        txt.setFile(true, fileName, fileSize);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new com.nhom11.chatcomp.Chat_Item();

        setLayer(txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom11.chatcomp.Chat_Item txt;
    // End of variables declaration//GEN-END:variables
}
