/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.chatcomp;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author btdun
 */
public class Chat_File extends javax.swing.JPanel {

    /**
     * @return the right
     */
    public boolean isRight() {
        return right;
    }

    /**
     * @param right the right to set
     */
    public void setRight(boolean right) {
        this.right = right;
        setBackground((right ? new Color(0,111,205) : new Color(153,153,153)));
    }

    /**
     * Creates new form Chat_File
     */
    public void setFileName(String fileName){
        lbFIleName.setText(fileName);
    }
    public void setFIleSize(String fileSize){
//        lbFIleSize.setForeground((right ? new Color(0,0,0) : new Color(102,153,255)));
        lbFIleSize.setText(fileSize);
    }
    private boolean right;
    public Chat_File() {
        initComponents();
        
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), getHeight(), getHeight());
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress2 = new com.nhom11.swing.Progress();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbFIleName = new javax.swing.JLabel();
        lbFIleSize = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 111, 205));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setOpaque(false);

        progress2.setForeground(new java.awt.Color(255, 255, 255));
        progress2.setValue(50);
        progress2.setProgressType(com.nhom11.swing.Progress.ProgressType.FILE);

        jLayeredPane1.setLayout(new java.awt.GridLayout(2, 1));

        lbFIleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbFIleName.setText("My Fille name");
        jLayeredPane1.add(lbFIleName);

        lbFIleSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbFIleSize.setForeground(new java.awt.Color(0, 0, 204));
        lbFIleSize.setText("4MB");
        jLayeredPane1.add(lbFIleSize);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(progress2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbFIleName;
    private javax.swing.JLabel lbFIleSize;
    private com.nhom11.swing.Progress progress2;
    // End of variables declaration//GEN-END:variables
}
