/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.chatcomp;

import com.nhom11.app.MessageType;
import com.nhom11.comp.MyButton;
import com.nhom11.emoji.Emoji;
import com.nhom11.emoji.Model_Emoji;
import com.nhom11.event.PublicEvent;
import com.nhom11.main.MainFrame;
import com.nhom11.model.Model_Send_Message;
import com.nhom11.model.Model_User_Account;
import com.nhom11.service.Service;
import com.nhom11.swing.ModernScrollBar;
import com.nhom11.swing.WrapLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author btdun
 */
public class Panel_More extends javax.swing.JPanel {

    /**
     * Creates new form Panel_More
     */
    public Panel_More() {
        initComponents();
        init();
    }

    public void init() {
        setLayout(new MigLayout("fillx, wrap", "[]", "[]3[]"));
        //Header
        Panel_Header = new JPanel();
        Panel_Header.setBackground(new Color(90,90,90));
        Panel_Header.setLayout(new BoxLayout(Panel_Header, BoxLayout.LINE_AXIS));
        Panel_Header.add(getButtonFile());
        Panel_Header.add(getButtonEmoji1());
        Panel_Header.add(getButtonEmoji2());
        add(Panel_Header, "w 100%, h 30!");
        //Details
        Panel_Details = new JPanel();
        Panel_Details.setLayout(new WrapLayout(WrapLayout.LEFT));
        JScrollPane sp = new JScrollPane(Panel_Details);
        sp.setBorder(null);
        sp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        sp.setVerticalScrollBar(new ModernScrollBar());
        add(sp, "w 100%, h 100%");
    }

    private JButton getButtonFile() {
        MyButton file = new MyButton();
        file.setIcon(new ImageIcon(getClass().getResource("/com/nhom11/icon/link.png")));
        file.addActionListener((ActionEvent ae) -> {
            JFileChooser fc = new JFileChooser();
            fc.showOpenDialog(MainFrame.getFrames()[0]);
        });
        return file;
    }
    public JButton setUpButton(Model_Emoji me){
        JButton b = new JButton();
        b.setIcon(me.getIcon());
        b.setName(me.getId() + "");
        b.addActionListener((ActionEvent e)->{
            PublicEvent.getInstance().getEventSendMessage().sendMessage(new Model_Send_Message(MessageType.EMOJI,Service.getInstance().getCurrent_User_Account().getUserID(),
            user.getUserID(),me.getId() + ""));
        });
        return b;
    }
    public void setUser(Model_User_Account user){
        this.user = user;
    }
    private JButton getButtonEmoji1() {
        MyButton emoj1 = new MyButton();
        emoj1.setIcon(Emoji.getInstance().getEmoji(1).toSize(25, 25).getIcon());
        emoj1.addActionListener((ActionEvent ae)->{
            Panel_Details.removeAll();
            for(Model_Emoji item : Emoji.getInstance().getStyle1()){
                Panel_Details.add(setUpButton(item));
            }
            Panel_Details.revalidate();
            Panel_Details.repaint();
        });
//Emoji.getInstance().getEmoji(1);
        return emoj1;
//        return new JButton();
    }

    private JButton getButtonEmoji2() {
        MyButton emoj1 = new MyButton();
//        emoj1.setIcon(Emoji.getInstance().getEmoji(21).getIcon());
        emoj1.setIcon(Emoji.getInstance().getEmoji(21).toSize(25, 25).getIcon());
        emoj1.addActionListener((ActionEvent ae)->{
            Panel_Details.removeAll();
            for(Model_Emoji item : Emoji.getInstance().getStyle2()){
                Panel_Details.add(setUpButton(item));
            }
            Panel_Details.revalidate();
            Panel_Details.repaint();
        });
        return emoj1;
//        return new JButton();

    }
    private JPanel Panel_Header;
    private JPanel Panel_Details;
    private Model_User_Account user;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
