/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom11.main;

import com.nhom11.event.EventImageView;
import com.nhom11.event.EventMain;
import com.nhom11.event.PublicEvent;
import com.nhom11.model.Model_User_Account;
import com.nhom11.service.Service;
import com.nhom11.swing.ComponentResizer;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author btdun
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Point p;
    int Default_Width,Default_Height;
    public MainFrame() {
        initComponents();
        init();
        initEvent();
    }
    //Size
    public Dimension DefaultSize = new Dimension(1170,698);
    public Dimension Screen_Size = Toolkit.getDefaultToolkit().getScreenSize();
    
    public Point getCenterLocation(){
        int X = (Screen_Size.width - Default_Width) / 2;
        int Y = (Screen_Size.height - Default_Height) / 2;
//        System.out.println(x + " " + y);
        Point p = new Point(X,Y);
//        System.out.println(p);
        return p;
    }
    public void init(){
        setIconImage(new ImageIcon(getClass().getResource("/com/nhom11/icon/meetme.png")).getImage());
        controlPanel2.setDrag(this);
        controlPanel2.setChangeSize(this);
        controlPanel2.setIconButton(this);
        ComponentResizer comp = new ComponentResizer();
        comp.setSnapSize(new Dimension(1,1));
        comp.registerComponent(this);
        comp.setMaximumSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));
        comp.setMinimumSize(new Dimension(800,600));
        
        Default_Width = getWidth();
        Default_Height = getHeight();
        view_image.setVisible(false);
        chatForm.setVisible(false);
        loading.setVisible(false);
        login.setVisible(true);
        
        //connect to Server
        Service.getInstance().connectToServer();
    }
    
    public void initEvent(){
        PublicEvent publicEvent = PublicEvent.getInstance();
        publicEvent.addEventImageView(new EventImageView(){
            @Override
            public void viewImage(Icon image) {
                view_image.viewImage(image);
                view_image.setVisible(true);
            }
            
        });
        
        PublicEvent.getInstance().setEventMain(new EventMain(){
            @Override
            public void showLoading(boolean show) {
                loading.setVisible(show);
            }

            @Override
            public void initChat() {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                chatForm.setVisible(true);
                login.setVisible(false);
                loading.setVisible(false);
                Service.getInstance().getClient().emit("list_user", Service.getInstance().getCurrent_User_Account().getUserID());
            }

            @Override
            public void setUser(Model_User_Account user) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                chatForm.setUser(user);
            }

            @Override
            public void updateUser(Model_User_Account user) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                 chatForm.updateUser(user);
            }
        
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        From_Panel = new javax.swing.JLayeredPane();
        loading = new com.nhom11.form.Loading();
        login = new com.nhom11.form.Login();
        view_image = new com.nhom11.form.View_Image();
        chatForm = new com.nhom11.form.ChatForm();
        controlPanel2 = new com.nhom11.comp.ControlPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        From_Panel.setBackground(new java.awt.Color(102, 102, 102));
        From_Panel.setForeground(new java.awt.Color(255, 255, 255));
        From_Panel.setLayout(new java.awt.CardLayout());
        From_Panel.add(loading, "card5");
        From_Panel.add(login, "card4");
        From_Panel.setLayer(view_image, javax.swing.JLayeredPane.POPUP_LAYER);
        From_Panel.add(view_image, "card3");
        From_Panel.add(chatForm, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(From_Panel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(controlPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(From_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane From_Panel;
    private com.nhom11.form.ChatForm chatForm;
    private com.nhom11.comp.ControlPanel controlPanel2;
    private com.nhom11.form.Loading loading;
    private com.nhom11.form.Login login;
    private com.nhom11.form.View_Image view_image;
    // End of variables declaration//GEN-END:variables
}
