/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.form;

import com.nhom11.chatcomp.Chat_Body;
import com.nhom11.chatcomp.Chat_Bottom;
import com.nhom11.chatcomp.Chat_Title;
import com.nhom11.event.EventSendMessage;
import com.nhom11.event.PublicEvent;
import java.awt.Color;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author btdun
 */
public class Chat extends javax.swing.JPanel {

    /**
     * Creates new form MenuLeft
     */
    public Chat() {
//        initComponents();
        init();
//        initEvent();
    }
    public void init(){
//        setBackground(Color.white);
        setLayout(new MigLayout("fillx", "0[fill]0", "0[40:40:]6[100%, bottom]6[shrink 0]6"));
        Chat_Title chatTitle = new Chat_Title();
        Chat_Body chatBody = new Chat_Body();
        Chat_Bottom chatBottom = new Chat_Bottom();
        PublicEvent.getInstance().setEventSendMessage(new EventSendMessage(){
            @Override
            public void sendMessage(String message) {
                chatBody.addItemRight(message);
            }
            
        });
        add(chatTitle, "wrap");
        add(chatBody, "wrap, growy");
        add(chatBottom, "h ::50%");
    }
    public void initEvent(){
        PublicEvent.getInstance().setEventSendMessage(new EventSendMessage(){
            @Override
            public void sendMessage(String message) {
                chat_Body.addItemRight(message);
            }
            
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chat_Body = new com.nhom11.chatcomp.Chat_Body();
        chat_Title = new com.nhom11.chatcomp.Chat_Title();
        chat_Bottom1 = new com.nhom11.chatcomp.Chat_Bottom();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chat_Body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
            .addComponent(chat_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(chat_Bottom1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chat_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chat_Body, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chat_Bottom1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom11.chatcomp.Chat_Body chat_Body;
    private com.nhom11.chatcomp.Chat_Bottom chat_Bottom1;
    private com.nhom11.chatcomp.Chat_Title chat_Title;
    // End of variables declaration//GEN-END:variables
}
