/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.form;

import com.nhom11.swing.ModernScrollBar;
import com.nhom11.comp.User_Item;
import javax.swing.JComponent;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author btdun
 */
public class MenuLeft extends javax.swing.JPanel {

    /**
     * Creates new form MenuLeft
     */
    public MenuLeft() {
        initComponents();
        init();
    }
    public void init(){
        List.setLayout(new MigLayout("fillx, wrap","0[fill]0","5[]5"));
        message.setSelected(true);
        showUser();
        sp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        sp.setVerticalScrollBar(new ModernScrollBar());
    }
    public void showUser(){
        List.removeAll();
        for(int i = 0;i < 20;i++){
            List.add(new User_Item("User" + i,"online","/com/nhom11/icon/user.png"));
        }
        resetGraphics(List);
        
    }
    public void showGroup(){
        List.removeAll();
        for(int i = 0;i < 5;i++){
            List.add(new User_Item("Group" + i,"online","/com/nhom11/icon/user.png"));
        }
        resetGraphics(List);
    }
    
    public void showBox(){
        List.removeAll();
        for(int i = 0;i < 5;i++){
            List.add(new User_Item("Box" + i,"online","/com/nhom11/icon/user.png"));
        }
        resetGraphics(List);
    }
    
    public void resetGraphics(JComponent comp){
        comp.repaint();
        comp.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        List = new javax.swing.JLayeredPane();
        Button_Box = new javax.swing.JPanel();
        message = new com.nhom11.comp.MyButton();
        group = new com.nhom11.comp.MyButton();
        box = new com.nhom11.comp.MyButton();

        sp.setBackground(new java.awt.Color(255, 255, 255));
        sp.setBorder(null);

        List.setBackground(new java.awt.Color(255, 255, 255));
        List.setOpaque(true);

        javax.swing.GroupLayout ListLayout = new javax.swing.GroupLayout(List);
        List.setLayout(ListLayout);
        ListLayout.setHorizontalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ListLayout.setVerticalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );

        sp.setViewportView(List);

        Button_Box.setBackground(new java.awt.Color(255, 255, 255));

        message.setBackground(new java.awt.Color(150, 202, 255));
        message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/message.png"))); // NOI18N
        message.setNormalIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/message.png"))); // NOI18N
        message.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/message_selected.png"))); // NOI18N
        message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageMouseClicked(evt);
            }
        });

        group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/group.png"))); // NOI18N
        group.setNormalIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/group.png"))); // NOI18N
        group.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/group_selected.png"))); // NOI18N
        group.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupMouseClicked(evt);
            }
        });

        box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/box.png"))); // NOI18N
        box.setNormalIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/box.png"))); // NOI18N
        box.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/box_selected.png"))); // NOI18N
        box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Button_BoxLayout = new javax.swing.GroupLayout(Button_Box);
        Button_Box.setLayout(Button_BoxLayout);
        Button_BoxLayout.setHorizontalGroup(
            Button_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_BoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Button_BoxLayout.setVerticalGroup(
            Button_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_BoxLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(Button_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(group, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            .addComponent(Button_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Button_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageMouseClicked
        if(SwingUtilities.isLeftMouseButton(evt))
        {
            message.setSelected(true);
            group.setSelected(false);
            box.setSelected(false);
            showUser();
        }
    }//GEN-LAST:event_messageMouseClicked

    private void groupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupMouseClicked
        if(SwingUtilities.isLeftMouseButton(evt))
        {
            message.setSelected(false);
            group.setSelected(true);
            box.setSelected(false);
            showGroup();
        }
    }//GEN-LAST:event_groupMouseClicked

    private void boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxMouseClicked
        if(SwingUtilities.isLeftMouseButton(evt))
        {
            message.setSelected(false);
            group.setSelected(false);
            box.setSelected(true);
            showBox();
        }
    }//GEN-LAST:event_boxMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button_Box;
    private javax.swing.JLayeredPane List;
    private com.nhom11.comp.MyButton box;
    private com.nhom11.comp.MyButton group;
    private com.nhom11.comp.MyButton message;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
