/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.form;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.SwingUtilities;

/**
 *
 * @author btdun
 */
public class View_Image extends javax.swing.JPanel {

    /**
     * Creates new form View_Image
     */
    private Icon image;
    public View_Image() {
        initComponents();
    }
    public void viewImage(Icon image)
    {
        this.image = image;
        pic.setImageIcon(image);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g.setColor(new Color(0,0,0,200));
        g.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic = new com.nhom11.swing.Picture_Box();
        cmdSaveImage = new javax.swing.JButton();
        cmdBack = new javax.swing.JButton();

        setOpaque(false);

        cmdSaveImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/save.png"))); // NOI18N
        cmdSaveImage.setBorder(null);
        cmdSaveImage.setBorderPainted(false);
        cmdSaveImage.setContentAreaFilled(false);
        cmdSaveImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdSaveImage.setFocusable(false);
        cmdSaveImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdSaveImageMouseClicked(evt);
            }
        });

        cmdBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/back-01.png"))); // NOI18N
        cmdBack.setBorder(null);
        cmdBack.setBorderPainted(false);
        cmdBack.setContentAreaFilled(false);
        cmdBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBack.setFocusable(false);
        cmdBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdBackMouseClicked(evt);
            }
        });

        pic.setLayer(cmdSaveImage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pic.setLayer(cmdBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout picLayout = new javax.swing.GroupLayout(pic);
        pic.setLayout(picLayout);
        picLayout.setHorizontalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, picLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdSaveImage)
                .addGap(17, 17, 17))
            .addGroup(picLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cmdBack)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        picLayout.setVerticalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, picLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cmdBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 522, Short.MAX_VALUE)
                .addComponent(cmdSaveImage)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSaveImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdSaveImageMouseClicked
        System.out.println("Save function in development");
    }//GEN-LAST:event_cmdSaveImageMouseClicked

    private void cmdBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdBackMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cmdBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBack;
    private javax.swing.JButton cmdSaveImage;
    private com.nhom11.swing.Picture_Box pic;
    // End of variables declaration//GEN-END:variables
}
