/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.comp;

import com.nhom11.main.MainFrame;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author btdun
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        init();
    }
    public void init(){
        ExitButton.addActionListener((ActionEvent e) -> {
            //                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            System.exit(0);
        });
    }
    Point CurrentPlace;
    public void setDrag(JFrame frame){
//        System.out.println(getX() + " " + getY());
//        System.out.println(frame.getX() + " " + frame.getY());
        addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e) {
//                super.mousePressed(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                CurrentPlace = e.getPoint();
//                System.out.println(CurrentPlace);
            }
            
        });
        addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent e) {
//                super.mouseDragged(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                Point newPlace = e.getPoint();
//                System.out.println(newPlace);
                frame.setLocation(frame.getX() + newPlace.x - CurrentPlace.x, frame.getY() + newPlace.y - CurrentPlace.y);
            }
            
        });
    }
    
    //ChangeSize Button
    ImageIcon Minimize= new ImageIcon(getClass().getResource("/com/nhom11/icon/smallscreen-01.png"));
    ImageIcon Expand = new ImageIcon(getClass().getResource("/com/nhom11/icon/expand-icon-01.png"));
    boolean Full_Size = false;
    Point Full_Size_Loca = new Point(0,0);
    Point Defaultsize_Loca = new Point(375,191);
    public void setChangeSize(MainFrame f){
        ChangeSize.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                Full_Size = !Full_Size;
//                System.out.println(Full_Size);
                Dimension Current_Size = (Full_Size) ? f.Screen_Size  : f.DefaultSize;
                Defaultsize_Loca = f.getCenterLocation();
//                System.out.println(Defaultsize_Loca);
                Point Location = (Full_Size) ? Full_Size_Loca : Defaultsize_Loca;
//                f.setLocation(Location);
                f.setBounds(Location.x, Location.y, Current_Size.width, Current_Size.height);
                ImageIcon icon = (Full_Size) ? Minimize : Expand;
                ChangeSize.setIcon(icon);
//                f.getCenterLocation();
            }
            
        });
    }
    public void setIconButton(JFrame f){
        IconButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                f.setState(JFrame.ICONIFIED);
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitButton = new javax.swing.JButton();
        App_Name = new javax.swing.JLabel();
        ChangeSize = new javax.swing.JButton();
        IconButton = new javax.swing.JButton();

        ExitButton.setBackground(new java.awt.Color(255, 51, 51));
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/exit-button-01.png"))); // NOI18N
        ExitButton.setBorder(null);
        ExitButton.setBorderPainted(false);
        ExitButton.setContentAreaFilled(false);
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitButton.setFocusPainted(false);
        ExitButton.setFocusable(false);

        App_Name.setBackground(new java.awt.Color(255, 51, 51));
        App_Name.setForeground(new java.awt.Color(0, 0, 0));
        App_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        App_Name.setText("Chat Application");

        ChangeSize.setBackground(new java.awt.Color(102, 102, 255));
        ChangeSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/expand-icon-01.png"))); // NOI18N
        ChangeSize.setBorder(null);
        ChangeSize.setBorderPainted(false);
        ChangeSize.setContentAreaFilled(false);
        ChangeSize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ChangeSize.setFocusPainted(false);
        ChangeSize.setFocusable(false);

        IconButton.setBackground(new java.awt.Color(204, 204, 0));
        IconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/Tab-icon-01.png"))); // NOI18N
        IconButton.setBorder(null);
        IconButton.setBorderPainted(false);
        IconButton.setContentAreaFilled(false);
        IconButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IconButton.setFocusPainted(false);
        IconButton.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(App_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addGap(112, 112, 112)
                .addComponent(IconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ChangeSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(App_Name)
                .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangeSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel App_Name;
    private javax.swing.JButton ChangeSize;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton IconButton;
    // End of variables declaration//GEN-END:variables
}
