/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.comp;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author btdun
 */
public class User_Item extends javax.swing.JPanel {
    String Name,Status,Image_Path;

    /**
     * Creates new form User_Item
     */
    public User_Item() {
        initComponents();
    }
    public User_Item(String Name,String Status,String Image_Path){
        initComponents();
        this.Name = Name;
        this.Status = Status;
        this.Image_Path = Image_Path;
        init();
    }
    public void init(){
        Label_Name.setText(Name);
        Label_Status.setText(Status);
        Avatar.setImage(new ImageIcon(getClass().getResource(Image_Path)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Name = new javax.swing.JLabel();
        Label_Status = new javax.swing.JLabel();
        Avatar = new com.nhom11.swing.ImageAvatar();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 102, 102));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        Label_Name.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        Label_Name.setText("Name");

        Label_Status.setText("online");

        Avatar.setBackground(new java.awt.Color(153, 153, 153));
        Avatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/icon/user.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Name)
                    .addComponent(Label_Status))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Status))
                    .addComponent(Avatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new Color(190,190,190));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(Color.white);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom11.swing.ImageAvatar Avatar;
    private javax.swing.JLabel Label_Name;
    private javax.swing.JLabel Label_Status;
    // End of variables declaration//GEN-END:variables
}
